name: Deploy website

on: 
  push:
    branches: ["main"]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: yarn install

      - name: Install Netlify CLI globally
        run: npm install -g netlify-cli

      - name: Build project
        run: yarn build

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
